# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

D1_2nd <- function(n, f1, f2, rho) {
    .Call(`_iNEXT_IE_D1_2nd`, n, f1, f2, rho)
}

Dq_2nd <- function(n, f1, A, q, rho) {
    .Call(`_iNEXT_IE_Dq_2nd`, n, f1, A, q, rho)
}

Dq <- function(ifi, n, qs, f1, A, rho) {
    .Call(`_iNEXT_IE_Dq`, ifi, n, qs, f1, A, rho)
}

qDFUN <- function(q, Xi, n) {
    .Call(`_iNEXT_IE_qDFUN`, q, Xi, n)
}

qD_MLE <- function(q, ai) {
    .Call(`_iNEXT_IE_qD_MLE`, q, ai)
}

RD <- function(x, n, m, q) {
    .Call(`_iNEXT_IE_RD`, x, n, m, q)
}

